using System.Text;

namespace DesignPatterns.Behavioral.Template;

public abstract class DocumentGenerator
{
    // Template method (final algorithm)
    public string Generate()
    {
        var builder = new StringBuilder();

        AddHeader(builder);
        AddBody(builder);
        AddFooter(builder);

        return builder.ToString();
    }

    protected abstract void AddHeader(StringBuilder builder);
    protected abstract void AddBody(StringBuilder builder);

    protected virtual void AddFooter(StringBuilder builder)
    {
        builder.AppendLine("Generated by Template Method Engine");
    }
}